# Generated by Django 6.0.2 on 2026-04-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_administrador', models.CharField(blank=True, max_length=50, null=True)),
                ('email_administrador', models.CharField(blank=True, max_length=50, null=True)),
                ('password_administrador', models.CharField(blank=True, max_length=128, null=True)),
                ('cargo_administrador', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtividadesDiaria',
            fields=[
                ('id_atividade_diaria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_atividade_diaria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atividades_diaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BarreirasArquitetonicas',
            fields=[
                ('id_barreira_arquitetonica', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_barreira_arquitetonica', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barreiras_arquitetonicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BarreirasIdosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'barreiras_idosos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('data_contacto', models.DateTimeField(blank=True, null=True)),
                ('observacoes_contacto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespesasFixas',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('valor_despesa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despesas_fixas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoencasCronicas',
            fields=[
                ('id_doenca_cronica', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_doenca_cronica', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doencas_cronicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoencasIdosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'doencas_idosos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncaminhamentosRede',
            fields=[
                ('id_encaminhamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_encaminhamento', models.TextField(blank=True, null=True)),
                ('encaminhamento_feito', models.BooleanField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('tempo_resposta', models.IntegerField(blank=True, null=True)),
                ('observacoes_encaminhamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encaminhamentos_rede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id_entidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_entidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'entidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EscalaoRendimentos',
            fields=[
                ('id_escalao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_escalao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_exato', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escalao_rendimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_estado_civil', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FragilidadeIdoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'fragilidade_idoso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrequenciaContacto',
            fields=[
                ('id_frequencia_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_frequencia_contacto', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'frequencia_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrequenciaContactoSocial',
            fields=[
                ('id_frequencia_contacto_social', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_frequencia_contacto_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'frequencia_contacto_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_genero', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrauAutonomia',
            fields=[
                ('id_grau_autonomia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_grau_autonomia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'grau_autonomia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id_intervencao', models.AutoField(primary_key=True, serialize=False)),
                ('data_intervencao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_intervencao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intervencao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembrosAgregadoFamiliar',
            fields=[
                ('id_membro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_membro', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_nascimento', models.IntegerField(blank=True, null=True)),
                ('grau_parentesco', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'membros_agregado_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobilidade',
            fields=[
                ('id_mobilidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_mobilidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mobilidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id_nacionalidade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nacionalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelIsolamento',
            fields=[
                ('id_nivel_isolamento', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_isolamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nivel_isolamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'participar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblematicasIdentificadas',
            fields=[
                ('id_problematica', models.AutoField(primary_key=True, serialize=False)),
                ('nome_problematica', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'problematicas_identificadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuedasIdoso',
            fields=[
                ('id_queda', models.AutoField(primary_key=True, serialize=False)),
                ('data_queda', models.DateField(blank=True, null=True)),
                ('observacoes_queda', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quedas_idoso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacaoFamilia',
            fields=[
                ('id_relacao_familia', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_relacao_familia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'relacao_familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SinaisFragilidade',
            fields=[
                ('id_sinal_fragilidade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_fragilidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sinais_fragilidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoHabitacional',
            fields=[
                ('id_situacao_habitacional', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_situacao_habitacional', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'situacao_habitacional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoLaboral',
            fields=[
                ('id_situacao_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_situacao_laboral', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'situacao_laboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id_tipo_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_despesa', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'db_table': 'tipo_despesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacao',
            fields=[
                ('id_tipo_habitacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_habitacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIntervencao',
            fields=[
                ('id_tipo_intervencao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_intervencao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_intervencao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipologiaAgregadoFamiliar',
            fields=[
                ('id_tipologia', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipologia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipologia_agregado_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRendimento',
            fields=[
                ('id_tipo_rendimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_rendimento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_rendimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoResposta',
            fields=[
                ('id_tipo_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_resposta', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'db_table': 'tipo_resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUtente',
            fields=[
                ('id_tipo_utente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_utente', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_tipo_utente', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_utente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utentes',
            fields=[
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_utente', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaUtente',
            fields=[
                ('id_zona_utente', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_zona_utente', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zona_utente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtentesIdosos',
            fields=[
                ('id_utente', models.OneToOneField(db_column='id_utente', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='appsocial.utentes')),
                ('vive_sozinho', models.BooleanField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('familiar_referencia', models.TextField(blank=True, null=True)),
                ('medicacao_diaria', models.BooleanField(blank=True, null=True)),
                ('dificuldade_acesso_saude', models.BooleanField(blank=True, null=True)),
                ('acompanhamento_reg', models.BooleanField(blank=True, null=True)),
                ('participa_atividades_fr', models.BooleanField(blank=True, null=True)),
                ('tristesa_depressao', models.BooleanField(blank=True, null=True)),
                ('luto_recente', models.BooleanField(blank=True, null=True)),
                ('aquecimento_adeq_inv', models.BooleanField(blank=True, null=True)),
                ('seguranca', models.TextField(blank=True, null=True)),
                ('necessidade_adptacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utentes_idosos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtentesSocioEconomicas',
            fields=[
                ('id_utente', models.OneToOneField(db_column='id_utente', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='appsocial.utentes')),
                ('risco_social', models.BooleanField(blank=True, null=True)),
                ('observacoes_utente', models.TextField(blank=True, null=True)),
                ('criterio_risco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utentes_socio_economicas',
                'managed': False,
            },
        ),
    ]
